idf_component_register(
    SRCS
        "main.c"
        "wifi/attack.c"
        "wifi/attack_methods.c"
        "wifi/attack_dos.c"
        "wifi/attack_eviltwin.c"
        "wifi/attack_jammer.c"
        "wifi/attack_bluetooth_jammer.c"
        "wifi/attack_beacon_spam.c"
        "wifi/attack_deauth.c"
        "wifi/attack_ducky.c"
        "wifi/attack_pmkid.c"
        "wifi/wifi_pass_verifier.c"
        "utils/bw16_uart.c"
        "utils/management_helper.c"
        "hardware/buzzer_led.c"
    INCLUDE_DIRS
        "."
        "wifi"
        "utils"
        "hardware"
    REQUIRES
        esp_wifi
        nvs_flash
        esp_event
        esp_netif
        esp_http_server
        esp_timer
        lwip
        cjson
        driver
        freertos
        bt
        esp_hw_support
        spiffs
        esp_tinyusb
        wsl_bypasser
        wifi_controller
        webserver
)
